language: node_js
node_js:
- lts/*
install:
- yarn
script:
- yarn build
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: build
  on:
    branch: master
env:
  global:
    secure: jo3+/oeReG7uhK7+QJZ8ydpYShVobLB2NwvSEdJ5xBAoZxaHFn4FVAxjwpBt79TVks4j807yPs6gpaLCiWnRUNoWxPS8tmEb2mRyH9rS90ZbFhz8OS94pfJQH/JnEnpGlziZllUrVrKNGJDgAQ3O2XX65uqWps9fqfTO07X9BDQXqluIy291zqtYmPt6uUIcGODt3p2gZV9J9S/U4EHV/5SkCx2WW0VwSKAIB22rhHNfemUqS/vnJrO3972bUouzNdDMY3UneqmygLY871L1eVusjL7V2zB9pSrUBKxROFwZsMkhuRn2M1aWOIrRKOl2Oit4f90vaRbXrHY+U39GzbbvejJnLgK5cY6PMVvMr3WBLWAsKNzK0ZR6LMF3Wnz4c2XY1KrVAzjeKyseNCLB29YCC4N+wu7oOIwACPND2x3hAGBkXAFwojyP62z3VQvXBcstiNOXuIezDD1bsjESMfuqQgwsyKHMmiq78TbrfKUhYQvi9kXJy7GXX6gYLr+FERN5zjvJiHu0YyCCl67aCwwL1rhNfs8iFSfLbQAfP2RZBZ4y9I3xcUvp1hFSnr3kPY6Icp2IbKs+ALBBc51PBMnQFjkC4mShI1mH2HhTkhno1KceaMLWFPkJHHHeaNQlk6JleTktiLzWoU5fATWUdzUV9Evt1VBeIROfDgRiS20=
