language: node_js
node_js:
- lts/*
install:
- yarn
script:
- yarn build
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: build
  on:
    branch: master
env:
  global:
    secure: dYY4bMzwZfyeDFLWg34+msxSCe47nhXz1podMfNbdPLZwdAgzhlgtudRl1ALbmNv04cgCrXGgxxJlwtc4BKoLU1h3BA2shzXlZSyovTRqSvd2HFmoCAlN4qjDTTtKwB1RBntRN8iV6eG2isgacPsNd/VDlP2gN38OU72LWZN4Nbgu90b2CFMggdnn5VK7HdnsXAak4uFTGe8wZfEquqzxBOuyajIUscKlSw+yVoPY8mBJdybts8ZNqrbu4mwRWYVJsnvh+ozuglcyabcJYVLYqHU34t70DnMze0yGwL+NEfh4EEzMKhvgM0JkwO7Yd/1/7qjZ1HHNCHyboAvqkFE7cPmhWiAYhg2plp84tvwUOqDYNDDLuyGclvQDf75cxBQCsccIkK0i7KsF4q2YFAQSH6uhMWObEGODPpn4bTTLFoCOgffiFgfyJAPhUh7NLsstqE1AiUmG78Zucss2wnc/tx/mYidLHN5zgH7YK5KJ+l/dTgHnOXPZ0JRFRo7soF8pTZ+fGmRjcjeQW57rcYkae7et2OLFxaiSQfFnI3WT5mS/hrtWRe6x902rVO5HQbx3V1PCSbRq4xueX570FIPtqIXJUhJfeKuwb1UpPY9fJZ7EoOss9cpB/lVnLzB1H41hZzEjg7X9UOfrbqKecw/N+zFLstp2e6GSx48wTKnydQ=
