language: node_js
node_js:
- lts/*
install:
- yarn
script:
- yarn build
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: build
  on:
    branch: master
env:
  global:
    secure: HTSS0yTh0PLHMAMyH41T7NrQnhqeN7fb2P/Sg8n3OxbqcimPbXlCh/oppZ/TqCsBUPDxorOKzL+C1lWiujlvhEx6I5JCKxSnY8vPQhAk/pMNXQZHlSL/qgwNJsauhfgcZNfxd2nM0wrZ28IYZF8AOnNSPATEfEqdVsd1YHwd6z/BlrxnBv2v3k98zGRws05pT4soQsw0UA6CpzUCzabtl+FkdcHCtClmlIEZHGBe2H1MD9vrAorhVz03ZlWph/43M0UzvmZ/p7ptaUwepdlKxBTxMosrLhPtBI7CGkO+bOtaev6jJAAFxMd+yR7Ujb/AS1vB/iUnSTdi25QSJa1zsDqd+7bXOj6ygGQjcnamsdJO2xhcxcI+m22xYGba08yfA1U/oCtyrqESzPUNlRJwYBb3jt/h4V5U3G4bwin2anCewvPs9Rmv5ZdaU0Y4OYm+chppzi1o4hMKNyD/toC658mjM5Dh1RkbTCfpZehz68s5MUHnhp+z7So/voM1DcM5rmh9BVosW4ZyrnAJdHEMs+VdYU5XA7rH8gDrTWfOwRFwAyTjWrpdRSWY7F9ch84C13VHgohlqusz8dcnclnN7n5RKnzQndedp4udqMzUxeTMxac/OX1Z1t/fEpO62Bl5JmY7/xYX5SD7TDNMsS0PgoP7NCiKsY/iNtyvUBUiQrY=
